import jsPDF from 'jspdf';

export const generateStatsReport = async (statsData, username) => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();

    // Header
    pdf.setFillColor(79, 70, 229); // Indigo
    pdf.rect(0, 0, pageWidth, 40, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.text('CareSphere Health Report', pageWidth / 2, 20, { align: 'center' });

    pdf.setFontSize(12);
    pdf.text(`Generated for: ${username}`, pageWidth / 2, 30, { align: 'center' });
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 36, { align: 'center' });

    // Reset text color
    pdf.setTextColor(0, 0, 0);

    // Summary Stats
    let yPos = 55;
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    pdf.text('Summary Statistics', 15, yPos);

    yPos += 10;
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'normal');

    const stats = [
        { label: 'Active Medicines', value: statsData.totalMedicines },
        { label: 'Doses Taken', value: statsData.takenCount },
        { label: 'Doses Missed', value: statsData.missedCount },
        { label: 'Adherence Rate', value: `${statsData.adherenceRate}%` },
    ];

    stats.forEach((stat, index) => {
        pdf.text(`${stat.label}: ${stat.value}`, 20, yPos + (index * 8));
    });

    // Medicine Breakdown
    yPos += 50;
    pdf.setFontSize(16);
    pdf.setFont(undefined, 'bold');
    pdf.text('Medicine-wise Adherence', 15, yPos);

    yPos += 10;
    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');

    statsData.medicineStats.forEach((med, index) => {
        if (yPos > 270) {
            pdf.addPage();
            yPos = 20;
        }
        pdf.text(`${med.name}: ${med.adherenceRate}% (${med.taken}/${med.total} doses)`, 20, yPos);
        yPos += 7;
    });

    // Footer
    pdf.setFontSize(10);
    pdf.setTextColor(128, 128, 128);
    pdf.text('Generated by CareSphere - Your Health Companion', pageWidth / 2, 290, { align: 'center' });

    // Save the PDF
    pdf.save(`CareSphere_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
